version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    image: with-docker-multi-env-production
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:4000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: express_backend
    image: backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
#     depends_on:
#       - database

#   database:
#     image: postgres
#     container_name: postgres_db
#     restart: always
#     env_file:
#       - .env # Reference to the .env file
#     volumes:
#       - pg_data:/var/lib/postgresql/data # Persist data
#     ports:
#       - "5432:5432"

# volumes:
#   pg_data:
